build:
  analysers: true
  spellers: true
  grammar-checkers: false
  tts-textproc: false
  hyphenators: false
check:
  analysers: true
  spellers: true
  grammar-checkers: false
  tts-textproc: false
  hyphenators: false
